"""rename example_text column to example

Revision ID: 061d0aa21a67
Revises: d6457e5ad9b7
Create Date: 2025-06-04 11:06:51.635146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061d0aa21a67'
down_revision: Union[str, None] = 'd6457e5ad9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examples', sa.Column('example', sa.Text(), nullable=False))
    op.drop_column('examples', 'example_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examples', sa.Column('example_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('examples', 'example')
    # ### end Alembic commands ###
