"""Create tables

Revision ID: d6457e5ad9b7
Revises: 
Create Date: 2025-06-04 10:56:22.584853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6457e5ad9b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character', sa.CHAR(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_digraph', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('letter_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['letter_id'], ['letters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('example_text', sa.Text(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    op.drop_table('examples')
    op.drop_table('words')
    op.drop_table('letters')
    # ### end Alembic commands ###
